# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8a8ac480fc43b5bce19015fb8c567a880a502a0a52768573f268b9d863bb63a9e3f0a946accbd5d98510153c8308f1e91ed9c6f2e5c9d5ac40de4f361dcfa5c

test:
  secret_key_base: 57afd0aa0de6954d9a00922bbdb8f326e533e824a2c71ad9333fed4b4383ef1be1ba3a9e01151e848c205da927de804d39cbe4f976edac00abcb68ff75979ccf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
